### ISSUE TITLE
How to use with composition api?

### ISSUE THREAD

**Issue by ahoiroman** [MeForma/vue-wait-for#1]
Hi and thanks a lot for your great and lightweight alternative to vue-wait.

Any idea how I can use this within the `setup()` of the composition api?

If I do something like

```
import wait from "@meforma/vue-wait-for";

createApp(App).use(wait).mount('#app')
```

And try to use it like this:

```
const onSubmit = handleSubmit (async values => {
            this.$wait.start('post');
 });
```

I am getting an error.

**Comment by jprodrigues70** [comment]
> Hi and thanks a lot for your great and lightweight alternative to vue-wait.
> 
> Any idea how I can use this within the `setup()` of the composition api?
> 
> If I do something like
> 
> ```
> import wait from "@meforma/vue-wait-for";
> 
> createApp(App).use(wait).mount('#app')
> ```
> 
> And try to use it like this:
> 
> ```
> const onSubmit = handleSubmit (async values => {
>             this.$wait.start('post');
>  });
> ```
> 
> I am getting an error.

**Comment by jprodrigues70** [comment]
Happy for your comment. I think You have to `provide` and `inject`!

```ts
app.use(wait).provide('wait', app.config.globalProperties.$wait);
```

```ts
    setup(props, context): any {
        const wait: any = inject('wait');
        wait.start('setup!');
    }
```

**Comment by ahoiroman** [comment]
That works fine! Thanks a lot :-) And thanks again for your great work.

**Comment by jprodrigues70** [comment]
You are welcome! 😄
